Description: >
    Author: Mudathir Lawal / School of Cloud Computing, Udacity;
    This template deploys a high availability infrastructure as 
    code for a project app named Udagram. LastUpdate: 09/04/2020

Parameters:
    
    EnvironmentName: 
        Description: A name that indicates the cloud environment 
            inside which the infrastructure exists. It is prefixed 
            to the name of each resource on the network.
        Type: String

    VpcCIDR:
        Description: Stipulates the IP address range for this VPC.
        Type: String
        Default: 10.0.0.0/16
    
    PrivateSubnet1CIDR:
        Description: IP address range for PrivateSubnet1 in AZ1.   
        Type: String
        Default: 10.0.1.0/24

    PrivateSubnet2CIDR:
        Description: IP address range for PrivateSubnet2 in AZ2. 
        Type: String
        Default: 10.0.3.0/24

    PublicSubnet1CIDR:
        Description: IP address range for PublicSubnet1 in AZ1. 
        Type: String
        Default: 10.0.0.0/24

    PublicSubnet2CIDR:
        Description: IP address range for PublicSubnet2 in AZ2. 
        Type: String
        Default: 10.0.4.0/24

Resources: 
        
    UdagramVPC: 
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: !Ref VpcCIDR
            EnableDnsHostnames: true
            Tags: 
                - Key: Name 
                  Value: !Ref EnvironmentName
            
    InternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties:
            Tags:
                - Key: Name
                  Value: !Ref EnvironmentName
            
    InternetGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            InternetGatewayId: !Ref InternetGateway
            VpcId: !Ref UdagramVPC
