Description: >
    Author: Mudathir Lawal / School of Cloud Computing, Udacity; 
    This template deploys the servers and other related infrastructure
    that exist on the Udagram cloud architecture. LastUpdate: 11/04/2020

 Parameters:

     EnvironmentName: 
         Description: The name prefixed to resource names to indicate the 
             cloud environment to which they belong.
         Type: String      

Resources:
    Resources:
  
  LBSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http access to load balancer
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPC-ID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
